syntax on
set nocompatible
filetype plugin on
" Disable the default Vim startup message.
set shortmess+=I
" Show line numbers.
set number
set relativenumber
" Tabs and spaces
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
" Always show status line.
set laststatus=2
" backspace over anything.
set backspace=indent,eol,start
set hidden
set ignorecase
set smartcase
" Search as you type
set incsearch
nmap Q <Nop> " 'Q' in normal mode enters Ex mode. You almost never want this.
" Disable audible bell
set noerrorbells visualbell t_vb=
" Enable mouse support
set mouse+=a
" Yea...
nnoremap <Left>  :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up>    :echoe "Use k"<CR>
nnoremap <Down>  :echoe "Use j"<CR>
" ...and in insert mode
inoremap <Left>  <ESC>:echoe "Use h"<CR>
inoremap <Right> <ESC>:echoe "Use l"<CR>
inoremap <Up>    <ESC>:echoe "Use k"<CR>
inoremap <Down>  <ESC>:echoe "Use j"<CR>

" Vim Plug
call plug#begin('.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'preservim/nerdtree'
" Plug 'vim-airline/vim-airline'
" Plug 'vim-airline/vim-airline-themes'
call plug#end()

" Must have that gruvbox all nice and dandy.
set termguicolors
let g:gruvbox_bold=1
let g:gruvbox_italic=1
let g:gruvbox_italicize_comments=1
let g:gruvbox_contrast_dark = ('medium')

" Annoying hack, because Alacritty is a sissy wench.
colorscheme blue
colorscheme gruvbox

